# Generated by Django 4.2 on 2023-04-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
