# Generated by Django 4.2 on 2023-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_pic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
