# Generated by Django 4.2 on 2023-04-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productmodel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusmodel',
            old_name='msg',
            new_name='message',
        ),
    ]
