# Generated by Django 4.2 on 2023-04-12 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_msg_contactusmodel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ProductImagesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='app.productmodel')),
            ],
            options={
                'db_table': 'product-images',
            },
        ),
    ]
