# Generated by Django 4.2 on 2023-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_productmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='img',
            field=models.ImageField(default='', upload_to='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
