# Generated by Django 4.2 on 2023-04-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productmodel_img_productmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='carpet_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(default='b9367b0f-44ff-40d7-88a7-6f944fb037a5', on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='app.categorymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='date_of_purchase',
            field=models.DateField(default='2020-10-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='fuel',
            field=models.CharField(blank=True, choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL'), ('CNG', 'CNG'), ('OTHERS', 'OTHERS')], default=('PETROL', 'PETROL'), max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_furnished',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_parking_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='km_driven',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='no_of_rooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='property_type',
            field=models.CharField(blank=True, choices=[('APPARTMENT', 'APPARTMENT'), ('BUNGLOW', 'BUNGLOW'), ('FARMHOUSE', 'FARMHOUSE')], default=('APPARTMENT', 'APPARTMENT'), max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('MANNUAL', 'MANNUAL'), ('AUTO', 'AUTO')], default=('MANNUAL', 'MANNUAL'), max_length=50, null=True),
        ),
    ]
