# Generated by Django 4.2 on 2023-04-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productmodel_brand_productmodel_carpet_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagesmodel',
            name='image',
            field=models.ImageField(upload_to='related_images'),
        ),
        migrations.AlterField(
            model_name='productimagesmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_images', to='app.productmodel'),
        ),
    ]
