# Generated by Django 4.2 on 2023-04-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_productimagesmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(blank=True, choices=[('APPLE', 'APPLE'), ('SAMSUNG', 'SAMSUNG'), ('ONEPLUS', 'ONEPLUS'), ('REALME', 'REALME'), ('NOKIA', 'NOKIA'), ('MOTOROLLA', 'MOTOROLLA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='fuel',
            field=models.CharField(blank=True, choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL'), ('CNG', 'CNG'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='property_type',
            field=models.CharField(blank=True, choices=[('APPARTMENT', 'APPARTMENT'), ('BUNGLOW', 'BUNGLOW'), ('FARMHOUSE', 'FARMHOUSE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('MANNUAL', 'MANNUAL'), ('AUTO', 'AUTO')], max_length=50, null=True),
        ),
    ]
