# Generated by Django 4.2 on 2023-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_productmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='location',
            field=models.CharField(choices=[('MARGAO', 'MARGAO'), ('PANJIM', 'PANJIM'), ('VASCO', 'VASCO'), ('MAPUSA', 'MAPUSA'), ('PONDA', 'PONDA'), ('VALPOI', 'VALPOI')], default=('MARGAO', 'MARGAO'), max_length=50),
        ),
    ]
